daysUntilStale: 14
daysUntilClose: 7
exemptLabels:
  - "bug: confirmed"
  - "in progress"
staleLabel: stale
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity.
closeComment: false
only: issues
